openapi: 3.0.0
servers:
  - description: Адрес приложения Creatio
    url: https://<адрес приложения>
info:
  version: "1.0.0"
  title: Интеграция с MDM
  description: |
    Описаны 2 точки интеграции с MDM. Для добавления контактов используется точка `/KmkContactService/Contacts`, для заказов - `/KmkOrderService/Orders`
#   contact:
#     email: you@your-company.com
#   license:
#     name: IIS
#     url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: anonymous
    description: |
      Точка для получения авторизационных кук и `BPMCSRF-токена` для аутентификации внешних запросов в приложении
  - name: default
    description: |
      Точки для добавления/обновления контактов и заказов в Creatio

paths:
  /ServiceModel/AuthService.svc/Login:
    post:
      tags:
        - anonymous
      summary: Запрос для аутентификации (анонимный)
      operationId: Auth
      parameters:
        - in: header
          name: ForceUseSession
          description: Заголовок для принудительного использования уже существующей сессии
          schema:
            type: boolean
            example: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Creds'
        description: "Используется для аутентификации других методов для получения `BPMCSRF-токена`"
      responses:
        '200':
          description: 'Результат запроса сервиса аутентификации. Возвращает 200 ОК даже при неправильных данных входа. Успешная авторизация вернет `"Code": 0`'
          headers:
            Set-Cookie:
              schema: 
                type: string
                example: "BPMCSRF=nCLTbvecrxFS5nc1afIJmO"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: bad input parameter
  /0/rest/KmkContactService/Contacts:
    post:
      # security:
      #   - cookieAuth: []
      parameters: 
        - in: header
          name: cookie
          schema:
            type: string
            example: "BPMCSRF=nCLTbvecrxFS5nc1afIJmO"
        - in: header
          name: BPMCSRF
          schema:
            type: string
            example: "nCLTbvecrxFS5nc1afIJmO"
      summary: "Точка интеграции для добавления/изменения контактов"
      operationId: CreateContacts
      description: "Метод для создания/обновления контактов в Creatio. Для выполнения запроса требуется `BPMCSRF-токен` и `Cookie` от запроса авторизации"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ContactList"
        description: "Данные о контакте"
      responses:
        '200':
          description: "Количество добавленных/обновленных контактов контактов"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactResponse'
  /0/rest/KmkOrderService/Orders:
    post:
      # security:
      #   - cookieAuth: []
      parameters: 
        - in: header
          name: cookie
          schema:
            type: string
            example: "BPMCSRF=nCLTbvecrxFS5nc1afIJmO"
        - in: header
          name: BPMCSRF
          schema:
            type: string
            example: "nCLTbvecrxFS5nc1afIJmO"
      summary: "Точка интеграции для добавления/изменения заказов"
      operationId: CreateOrders
      description: "Метод для создания/обновления заказов в Creatio. Для выполнения запроса требуется `BPMCSRF-токен` и `Cookie` от запроса авторизации"
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/OrderList"
        description: "Данные о заказе"
      responses:
        '200':
          description: "Количество добавленных/обновленных заказов"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
components:
  # securitySchemes:
  #   cookieAuth:
  #     type: apiKey
  #     in: cookie
  #     name: BPMCSRF
  schemas:
    ContactList:
      type: object
      properties:
        contacts:
          type: array
          items: 
            type: object
            required:
              - UniqueIdentifier
              - Name
            properties:
              UniqueIdentifier:
                type: string
              Name:
                type: string
              Surname: 
                type: string
              MiddleName:
                type: string
              MobilePhone:
                type: string
              Email:
                type: string
              BirthDate:
                type: string
                format: date
            example: 
              - UniqueIdentifier: "1"
                Name: "Alex"
                Surname: ""
                MiddleName: ""
                MobilePhone: "+79995557766"
                Email: "email@mail.com"
                BirthDate: "23.12.2012"
              - UniqueIdentifier: "2"
                Name: "Victor"
                Surname: ""
                MiddleName: ""
                MobilePhone: "+79995557222"
                Email: "email@mail.ru"
                BirthDate: "23.12.1977"
              - UniqueIdentifier: ""
                Name: "John"
                Surname: ""
                MiddleName: ""
                MobilePhone: "+79995557765"
                Email: "email@mail.com"
                BirthDate: "23.12.2011"
              - UniqueIdentifier: "3"
                Name: ""
                Surname: ""
                MiddleName: ""
                MobilePhone: "+79995557765"
                Email: "email@mail.com"
                BirthDate: "23.12.2011"  

    OrderBase:
      type: "object"
      required:
      - "IDClient"
      - "IDOrder"
      - "OrderStatus"
      - "Type"
      - "CreatedOn"
      - "DepartureCity"
      - "ArrivalСity"
      - "DepartureDate"
      - "ArrivalDate"
      properties:
        IDClient:
          type: "string"
        IDOrder:
          type: "string"
        CreatedOn:
          type: "string"
          format: "date-time"
        ArrivalСity:
          type: "string"
        DepartureCity:
          type: "string"
        DepartureDate:
          type: "string"
          format: "date-time"
        ArrivalDate:
          type: "string"
          format: "date-time"
        LinkTripSurvey:
          type: "string"
          format: "url"
          nullable: true
        LinkNPSSurvey:
          type: "string"
          format: "url"
          nullable: true
        Type:
          type: "string"
        OrderStatus:
          type: "string"

    OrderAvia:
      example:
        IDClient: "1"
        IDOrder: "1"
        CreatedOn: "2020-09-21T20:12:31+03:00"
        ArrivalСity: "Moscow"
        DepartureCity: "Saint-Peterburg"
        DepartureDate: "2020-09-21T20:12:00+03:00"
        ArrivalDate: "2020-09-21T23:34:00+03:00"
        Airline: "Pobeda"
        FlightNumber: "1234"
        NameDepartureAirport: "Domodedovo airport"
        LinkTripSurvey: "https://link-to-survey-flight.com"
        LinkNPSSurvey: "https://link-to-survey-flight.com"
        Type: "avia"
        OrderStatus: "paid"
        OrderNumber: "Заказ 134"

      required:
        - "Airline"
        - "FlightNumber"
        - "NameDepartureAirport"
      allOf:
        - $ref: '#/components/schemas/OrderBase'
        - type: object
          properties:
            Airline:
              type: "string"
            FlightNumber:
              type: "string"
            NameDepartureAirport:
              type: "string"

    OrderTrain:
      example:
        IDClient: "2"
        IDOrder: "2"
        CreatedOn: "2020-09-21T20:12:31+03:00"
        ArrivalСity: "Сочи"
        DepartureCity: "Москва"
        DepartureDate: "2020-09-21T20:12:00+03:00"
        ArrivalDate: "2020-09-22T10:15:00+03:00"
        NumberCar: "11"
        NumberTrain: "083М"
        NameDepartureStation: "Сочи"
        LinkTripSurvey: "https://link-to-survey-train.com"
        LinkNPSSurvey: "https://link-to-survey-train.com"
        Type: "train"
        OrderStatus: "created"
        OrderNumber: "Заказ 134"
      required:
        - "NumberCar"
        - "NumberTrain"
        - "NameDepartureStation"
      allOf:
        - $ref: '#/components/schemas/OrderBase'
        - type: object
          properties:
            NumberCar:
              type: "string"
            NumberTrain:
              type: "string"
            NameDepartureStation:
              type: "string"

    OrderBus:
      example:
        IDClient: "3"
        CreatedOn: "2020-09-21T20:12:31+03:00"
        ArrivalСity: "Москва"
        DepartureCity: "Санкт-Петербург"
        DepartureDate: "2020-09-21T20:12:00+03:00"
        ArrivalDate: "2020-09-22T06:15:00+03:00"
        LinkTripSurvey: "https://link-to-survey-bus.com"
        LinkNPSSurvey: "https://link-to-survey-bus.com"
        Type: "bus"
        OrderStatus: "refunded"
        OrderNumber: "Заказ 134"

      allOf:
        - $ref: '#/components/schemas/OrderBase'

    OrderList:
      type: "object"
      properties:
        orders:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/OrderAvia'
              - $ref: '#/components/schemas/OrderTrain'
              - $ref: '#/components/schemas/OrderBus'
              
    ContactResponse:
      type: object
      properties:
        Response:
          type: array
          items:
            type: object
            properties:
              Result: 
                type: string
              CRMId:
                type: string
                format: uuid
              UniqueIdentifier:
                type: string
              Description:
                type: string
          example:
          - Result: "created"
            CRMId: "3c0b9f2b-6def-40ba-bd3b-d6237e1c3146"
            UniqueIdentifier: "1"
            Description: ""
          - Result: "edited"
            CRMId: "ba6bc2f3-07dc-4375-bf73-e9b8b2c9cabe"
            UniqueIdentifier: "2"
            Description: ""  
          - Result: "error"
            CRMId: null
            UniqueIdentifier: null
            Description: "Не заполенен обязательный параметр UniqueIdentifier"
          - Result: "error"
            CRMId: null
            UniqueIdentifier: "3"
            Description: "Не заполенен обязательный параметр Name"
    OrderResponse:
      type: object
      properties:
        Response:
          type: array
          items:
            type: object
            properties:
              Result: 
                type: string
              CRMId:
                type: string
                format: uuid
              IDOrder:
                type: string
              Description:
                type: string
          example:
          - Result: "created"
            CRMId: "3c0b9f2b-6def-40ba-bd3b-d6237e1c3146"
            IDOrder: "1"
            Description: ""
          - Result: "edited"
            CRMId: "58014498-5df1-4ad2-8456-2c9fbe44ea1f"
            IDOrder: "2"
            Description: ""
          - Result: "error"
            CRMId: null
            IDOrder: null
            Description: "Не заполенен обязательный параметр IDOrder"
    Creds:
      type: object
      required:
        - UserName
        - UserPassword
      properties:
        UserName:
          type: string
          example: "Supervisor"
        UserPassword:
          type: string
          example: "Supervisor"
    AuthResponse:
      type: object
      properties:
        Code:
          type: integer
          example: 1
        Message:
          type: string
          example: "Вы ввели неправильный логин или пароль. Проверьте корректность введенных данных или обратитесь к системному администратору. Системный администратор может изменить пароль на странице пользователя"
        Exception:
          $ref: '#/components/schemas/Exception'
        PasswordChangeUrl:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        RedirectUrl:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
    Exception:
      type: object
      properties:
        HelpLink:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        InnerException:
          type: string
          example: 'System.Security.SecurityException'
        Message:
          type: string
          example: "Вы ввели неправильный логин или пароль. Проверьте корректность введенных данных или обратитесь к системному администратору. Системный администратор может изменить пароль на странице пользователя"
        StackTrace: 
          type: string
          example: ''
        Type: 
          type: string
          example: 'System.Security.SecurityException'
